# macOS profile
font_size 18.0

# Invisible titlebar — keeps traffic lights, moves title to menubar
macos_titlebar_color       background
macos_show_window_title_in menubar

# Mac-style zoom — fill screen, stay in Space
map ctrl+shift+z toggle_maximized
